### ISSUE TITLE
restrict function of bidsCopyRawFolder

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_SPM#106]
At the moment it copies the content of each `sub-xx` folder inluding stuff we might never use that COULD be in the BIDS dataset: an `eeg`, `meg`, `dwi` folder for example.

It also all the tasks at once, which might be OK as a default but we might want to make the function smarter.

- [x] filter by modality
- [x] filter by task
- [x] filter by other parameters (`acq`, `rec`, `dir`)

**Comment by CerenB** [comment]
not sure I 100% followed your message. 
You might be saying what I came here for: this function copies whatever in that `rawDir`... So When I'm running only `sub-009` (set it up in `getOptions.m`), it copies from `sub-001` to `sub-009`

**Comment by Remi-Gau** [comment]
Ah I was more referring to the fact that if you have dataset with non-MRI stuff it will also create a copy of this, which is NOT what we want (unless we just want to make sure we fill hard drives really quickly for no good reason).

So you are saying that even when you ask to process 1 subject, it will still take the data of all the subjects? 

If so... Then this is NOT the intended behavior (I think) and should be fixed...

Need more unit test... Again... Sigh...

**Comment by CerenB** [comment]
I think you did this one in your previous PR. thank you <3 !

**Comment by Remi-Gau** [comment]
Not quite I think. 

I want to make sure that `bidsCopyRawFolder` only copies the data from the required subjects and at the moment the test I have written does not check for that (yet): will keep this one open till I have updated the test. :wink:

**Comment by Remi-Gau** [comment]
It seems that `spm_bids` or  `bids.query` cannot look for modalities ('func', 'fmap', 'anat', 'dwi'...) for a specific session only so working on this will have to wait until that bug is fixed.

**Comment by Remi-Gau** [comment]
filtering on task is roughly "implemented" in 250

**Comment by CerenB** [comment]
@Remi-Gau would you consider adding restricting function of `reportBIDS` to selected/given subjects? At the moment it seemed that it's limited to the first subject. I haven't checked inside of the function to see if indeed it's only subject001 only.

**Comment by Remi-Gau** [comment]
At the moment, `reportBids` is just a wrapper for `bids.report` that can read from a specific subject / session:

See the help from `bids.report`

```
function report(BIDS, Subj, Ses, Run, ReadNII)
% Create a short summary of the acquisition parameters of a BIDS dataset
% FORMAT bids.report(BIDS, Subj, Ses, Run, ReadNII)
%
% INPUTS:
% - BIDS: directory formatted according to BIDS [Default: pwd]
%
% - Subj: Specifies which subject(s) to take as template.
% - Ses:  Specifies which session(s) to take as template. Can be a vector.
%         Set to 0 to do all sessions.
% - Run:  Specifies which BOLD run(s) to take as template.
% - ReadNII: If set to 1 (default) the function will try to read the
%             NIfTI file to get more information. This relies on the
%             spm_vol.m function from SPM.
%
% Unless specified the function will only read the data from the first
% subject, session, and run (for each task of BOLD). This can be an issue
% if different subjects/sessions contain very different data.
```

This  could just be passed up to the wrapper function if you need it.

**Comment by Remi-Gau** [comment]
see #276 as bidsCopy tends to delete stuff in a brutal way

**Comment by Remi-Gau** [comment]
It think this is pretty much done
