### ISSUE TITLE
voxDim - in getFuncVoxelDims function

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_SPM#112]
the voxel dimension in `normalisation` step seems to be set to` [2.7 2.6 2.7]` though my acquisition was/is 2.7 iso. Not sure what's the real issue here. 
first time I’ve run `bidsSpatialPrep` `voxDim = [2.7 2.6 2.7]`
second time `voxDim = [2.7 2.7 2.7]`
third time `voxDim = [2.6 2.6 2.6] `- I was stopping the function, debugging.

will keep watching on that.

**Comment by CerenB** [comment]
It looks like different runs are having different voxel dimensions when we use `spm_vol `function. 
```
>> hdr = spm_vol('/Users/xx/xx_run-012_bold.nii');

voxDim =

    2.7000    2.6000    2.7000

hdr = spm_vol('/Users/xx/xx_run-001_bold.nii');

voxDim =

    2.7000    2.6000    2.6000
```

**Comment by Remi-Gau** [comment]
@CerenB Can this be closed?

**Comment by CerenB** [comment]
sorry I'm a bit behind of all these. What did you decide at the end? I'll try to see new version PR to see the differences.

**Comment by Remi-Gau** [comment]
I don't remember what I chose. There was a rounding issue that we discussed on slack but I don't know if something was done about it.
