### ISSUE TITLE
[DOC] option to set manually the output dir 

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#157]
Why? In our workflow with gin, I have to separate the folder for the raw and the derivatives data. Default will remain 

```
fullfile(opt.dataDir, '..', 'derivatives', 'SPM12_CPPL');
```

in case `opt.derivativesDir` is not set manually

**Comment by marcobarilari** [comment]
ok, actually I think it is already implemented right?

in `setDerivativesDir`

line 14

```
  if ~isfield(opt, 'derivativesDir') || isempty(opt.derivativesDir)
    opt.derivativesDir = fullfile(opt.dataDir, '..', 'derivatives', 'SPM12_CPPL');
 end
```

so, in case in my `getOption` func I set 

`opt.derivativesDir  = 'myPathtTotheFolderBeforeDerivatevs`

should work.

**Comment by marcobarilari** [comment]
that was the quickest implementation 🥇

**Comment by Remi-Gau** [comment]
That is the expected behavior I have set up.

If `opt.derivativesDir` is not defined then a default path will be chosen relative to raw dataset.

See this test.

https://github.com/cpp-lln-lab/CPP_SPM/blob/master/tests/test_setDerivativesDir.m

`setDerivativesDir` is called by `getData` in case it is not provided with a specific directory to look into.

And `getData` is usually called very early by each workflow.

**Comment by marcobarilari** [comment]
good to know, I take this issue open as a reminder to add this info in the docs, WDYT?

**Comment by Remi-Gau** [comment]
YES !! I was thinking the same !!

**Comment by Remi-Gau** [comment]
```matlab
  %
  % Sets the derivatives folder and the directory where to save the SPM jobs.
  % The actual creation of the directory is done by
  % ``createDerivativeDir(opt)``.
  %
  % USAGE::
  %
  %   opt = setDerivativesDir(opt)
  %
  % :param opt:
  % :type opt: type
  %
  % :returns: - :opt: (structure)
  %
  % Examples:
  %   % opt.dataDir = '/home/remi/data';
  %   % opt.taskName = 'testTask';
  %   % opt = setDerivativesDir(opt);
  %   %
  %   % disp(opt.derivativesDir)
  %   %|| '/home/remi/data/../derivatives/cpp_spm'
  %   % 
  %   % disp(opt.opt.jobsDir)
  %   %|| '/home/remi/data/../derivatives/cpp_spm/JOBS/testTask
  %
  %   % opt.dataDir = '/home/remi/data';
  %   % opt.dataDir = '/home/remi/otherFolder';
  %   % opt.taskName = 'testTask';
  %   % opt = setDerivativesDir(opt);
  %   %
  %   % disp(opt.derivativesDir)
  %   %|| '/home/remi/otherFolder/derivatives/cpp_spm'
  %
  %   % opt.dataDir = '/home/remi/data';
  %   % opt.dataDir = '/home/remi/derivatives/preprocessing';
  %   % opt.taskName = 'testTask';
  %   % opt = setDerivativesDir(opt);
  %   %
  %   % disp(opt.derivativesDir)
  %   %|| '/home/remi/otherFolder/derivatives/preprocessing'
  %
  %
```

Here is the new help section for that function. 

It was giving some unexpected but nice behavior so I decided to document it.

**Comment by marcobarilari** [comment]
Sorry to come up to this with a bit of delay. It looks like that in the example there is something odd:

```
  %   % opt.dataDir = '/home/remi/data';

HERE BELOW SHOULD BE opt.derivativesDir

  %   % opt.dataDir = '/home/remi/otherFolder';  
  %   % opt.taskName = 'testTask';
  %   % opt = setDerivativesDir(opt);
  %   %
  %   % disp(opt.derivativesDir)
  %   %|| '/home/remi/otherFolder/derivatives/cpp_spm'
  %
  %   % opt.dataDir = '/home/remi/data';

HERE AS WELL

  %   % opt.dataDir = '/home/remi/derivatives/preprocessing'; 
  %   % opt.taskName = 'testTask';
  %   % opt = setDerivativesDir(opt);
  %   %
  %   % disp(opt.derivativesDir)
  %   %|| '/home/remi/otherFolder/derivatives/preprocessing'
```

**Comment by Remi-Gau** [comment]
> Sorry to come up to this with a bit of delay. It looks like that in the example there is something odd

Good catch !

Oh and by the way we might have to deced how we want to write down the examples in our help section.

The way I have done it here is a way that allows to test the documentation itself: automatically reads the help section and checks that the examples are valid.

It is convenient but it looks like BEEEEEP in the read the docs...

Any idea?

**Comment by marcobarilari** [comment]
mmh, not sure. I will check online some examples
