### ISSUE TITLE
sescounter not used in setBatchSmoothing

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#163]
in this file seems that `sescounter` is not used, is it?

https://github.com/cpp-lln-lab/CPP_SPM/blob/1530a1642a5213e0657646690b80a0c6f3a51cd9/src/batches/setBatchSmoothing.m#L20-L41

**Comment by Remi-Gau** [comment]
Correct !

Feel free to trash it !

**Comment by Remi-Gau** [comment]
> Feel free to trash it !

In a PR... To trash it with style

**Comment by marcobarilari** [comment]
done, closing this one
