### ISSUE TITLE
[DOC] Add demos' description in the docs

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#173]
from @Remi-Gau  in #157 

> Oh and by the way we might have to deced how we want to write down the examples in our help section.
> 
> The way I have done it here is a way that allows to test the documentation itself: automatically reads the help section and checks that the examples are valid.
> 
> It is convenient but it looks like BEEEEEP in the read the docs...
> 
> Any idea?

**Comment by marcobarilari** [comment]
I don't see doc for the demos, is it somewhere else?

**Comment by Remi-Gau** [comment]
if you mean stuff for the `demos` folder there is nothing and that's sad.

If you mean how to write "example" in  the help section  so we can  'test' those example with "moxdoc" then there is  template but the result look so bad in RTD that I very much want to drop it.

https://github.com/cpp-lln-lab/CPP_SPM/blob/dev/src/templates/templateFunctionExample.m

**Comment by marcobarilari** [comment]
I mean the first case, a section in the rtd where the demos are presented and it is explained what they actually can "teach"

**Comment by Remi-Gau** [comment]
Nope. There is none of that and this should be a low hanging fruit (esp with some details to "download" for the open neuro examples: cd datalad)

**Comment by marcobarilari** [comment]
Sounds good, I would add also some info on what the demos are an example of (e.g. group analysis, event related, etc). What do you think about re-opening this issue as a reminder?

Proposition to change the title in:

"Add demos' description in the docs"

**Comment by Remi-Gau** [comment]
Good with me
Go ahead
