### ISSUE TITLE
[ENH] Create workflow to deface all the anat files in a dataset.

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_SPM#176]
Actually we might want to have a similar simple workflow to deface all the anat files in a dataset.

_Originally posted by @Remi-Gau in https://github.com/cpp-lln-lab/CPP_SPM/issues/175#issuecomment-725874240_

**Comment by marcobarilari** [comment]
Run a batch to try, to me there is a difference in brightness, WDYT?

![deface-comp_001](https://user-images.githubusercontent.com/38101692/98955697-7b5ec180-24ff-11eb-932e-8ac2b720a94e.png)

**Comment by Remi-Gau** [comment]
I think this is because SPM checkreg has some normalization of the displayed intensity that is relative to the image. So if you have removed some voxels that could change the way they look even though the the data is actually the same.

**Comment by marcobarilari** [comment]
sorry, a have a lot of questions :)

1. we want to deface any anat data, do we? MP2RAGE included

2. `spm_BIDS(rawDir,'nii')` is not really happy with MP2RAGE, I think

```
Warning: Ignoring file "sub-pilot002_ses-001_acq-hires_part-mag_inv-1_MP2RAGE.nii" not matching
template. 
> In spm_BIDS>parse_filename (line 715)
  In spm_BIDS>parse_subject (line 163)
  In spm_BIDS (line 125)
  In spm_BIDS (line 37) 
Warning: Ignoring file "sub-pilot002_ses-001_acq-hires_part-mag_inv-2_MP2RAGE.nii" not matching
template. 
> In spm_BIDS>parse_filename (line 715)
  In spm_BIDS>parse_subject (line 163)
  In spm_BIDS (line 125)
  In spm_BIDS (line 37) 
Warning: Ignoring file "sub-pilot002_ses-001_acq-lores_part-mag_inv-1_MP2RAGE.nii" not matching
template. 
> In spm_BIDS>parse_filename (line 715)
  In spm_BIDS>parse_subject (line 163)
  In spm_BIDS (line 125)
  In spm_BIDS (line 37) 
Warning: Ignoring file "sub-pilot002_ses-001_acq-lores_part-mag_inv-2_MP2RAGE.nii" not matching
template. 
> In spm_BIDS>parse_filename (line 715)
  In spm_BIDS>parse_subject (line 163)
  In spm_BIDS (line 125)
  In spm_BIDS (line 37) 
```

**Comment by Remi-Gau** [comment]
> sorry, a have a lot of questions :)
> 
>     1. we want to deface any anat data, do we? MP2RAGE included

yes !!!

>     2. `spm_BIDS(rawDir,'nii')` is not really happy with MP2RAGE, I think

yes spm_bids does not like that. 

maybe try with bids-matlab: https://github.com/bids-standard/bids-matlab/blob/d0815ea702ea85ba9348ab2780f84564fbd5520f/%2Bbids/layout.m#L1

it has a tolerant flag that makes if more flexible. But I don't think that we are yet at the stage where non bids compliant files can still be "indexed" in the layout of bids.matlab.

**Comment by marcobarilari** [comment]
```
bids.layout(rawDir)
Warning: Ignoring file 'sub-pilot002_ses-001_acq-hires_part-mag_inv-1_MP2RAGE.nii' not matching
template. 
> In parse_filename (line 53)
  In bids.layout>parse_anat (line 185)
  In bids.layout>parse_subject (line 151)
  In bids.layout (line 123) 
Warning: Ignoring file 'sub-pilot002_ses-001_acq-hires_part-mag_inv-2_MP2RAGE.nii' not matching
template. 
> In parse_filename (line 53)
  In bids.layout>parse_anat (line 185)
  In bids.layout>parse_subject (line 151)
  In bids.layout (line 123) 
Warning: Ignoring file 'sub-pilot002_ses-001_acq-lores_part-mag_inv-1_MP2RAGE.nii' not matching
template. 
> In parse_filename (line 53)
  In bids.layout>parse_anat (line 185)
  In bids.layout>parse_subject (line 151)
  In bids.layout (line 123) 
Warning: Ignoring file 'sub-pilot002_ses-001_acq-lores_part-mag_inv-2_MP2RAGE.nii' not matching
template. 
> In parse_filename (line 53)
  In bids.layout>parse_anat (line 185)
  In bids.layout>parse_subject (line 151)
  In bids.layout (line 123) 
```

same old story, I think that at this point we might need to code using the hummer (`dir...`)

but hey, this is probably something to proposefor the bids-matlab repo :)

**Comment by marcobarilari** [comment]
ok no, I am stupid. Messing up with the folders added to the matlab paths.

So recently I have the reflex to open the script that I want to check calling them in the command window with `edit bids.layout'. This way I was opening the one from the CPP_BIDS repo and not the CPP_SPM one. I guess the one in the CPP_BIDS is not update cause it does not have the flag `tolerant` as you mentioned. 

Take home message: 

1. Adding stuff to the path is evil

2. Now I get why `virtualenv` from python is important

**Comment by Remi-Gau** [comment]
You are not stupid. I also had forgotten to update the bids-matlab sub-module in CPP_SPM. :wink: 

But yes adding those things permanently to the path can be a headache.

>     2\. Now I get why `virtualenv` from python is important

Now imaging how more important they if you imagined that Matlab was used regurlarly to run things on your operating system and that version of Matlab used by your OS is the 2010 version.


> `bids.layout(rawDir, true)` does not work for MP2RAGE as well

To add to the to do list of bids-matlab

**Comment by Remi-Gau** [comment]
> ps. `bids.layout(rawDir, true)` does not work for MP2RAGE as well

Do you know if this works with pybids though?

**Comment by Remi-Gau** [comment]
Closing this as we pretty much said that systematic defacing should be handled by other tools like bidsonym: https://github.com/PeerHerholz/BIDSonym

**Comment by marcobarilari** [comment]
do we have an issue reminding about this and pointing to BIDSonym? I can't find it.

ps: looking forward for the next labhack ;)

**Comment by Remi-Gau** [comment]
No issue here : might be better in the CPP_source codebase, no? 

https://github.com/cpp-lln-lab/CPP_sourceMRI
