### ISSUE TITLE
1 run of a task in only 1 of 2 sessions, getBoldFilename complains 

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#192]
I have encountered this error, it fails while setting the batch and looking for bold files in the second loop (ses-002) where there are no files related to my task and it is actually empty cause `bidsCopyRawFolder` did not copy those files related to other tasks.

```matlab
Index exceeds matrix dimensions.

Error in setBatchRealign (line 80)
                                                       runs{iRun}, ...

Error in bidsSpatialPrepro (line 70)
      [matlabbatch, voxDim] = setBatchRealign(matlabbatch, BIDS, subID, opt, action);
```

```
.
├── dataset_description.json
├── participants.json
├── participants.tsv
└── sub-001
    ├── ses-001
    │   ├── anat
    │   │   ├── sub-001_ses-001_T1w.json
    │   │   ├── sub-001_ses-001_T1w.nii
    │   │   └── sub-001_ses-001_T1w.nii.gz
    │   └── func
    │       ├── sub-001_ses-001_task-auditoryLoc_run-001_bold.json
    │       ├── sub-001_ses-001_task-auditoryLoc_run-001_bold.nii.gz
    │       ├── sub-001_ses-001_task-auditoryLoc_run-001_events.tsv
    │       ├── sub-001_ses-001_task-visualLoc_run-001_bold.json
    │       ├── sub-001_ses-001_task-visualLoc_run-001_bold.nii
    │       └── sub-001_ses-001task-visualLoc_run-001_events.tsv
    └── ses-002
```

**Comment by marcobarilari** [comment]
quick workaround is delating the folder for ses-002

**Comment by Remi-Gau** [comment]
So basically, we need to make sure that `bidsCopyRawFolder` does not create folders of other sessions if they don't contain the task of interest, right?

**Comment by marcobarilari** [comment]
yep

**Comment by marcobarilari** [comment]
update: running the second task that is only in session and it is complaining again. I have to move the second task in ses-001. No time to fix this now so I have to use this stupid workaround. Please, forgive me :(

**Comment by Remi-Gau** [comment]
No worries. But definitely good to know to fix that later.

**Comment by marcobarilari** [comment]
though, @fedefalag had a similar problem but I suspect they are unrelated. Do you confirm?

**Comment by Remi-Gau** [comment]
yup this was a `master` and `dev` branch issue

**Comment by Remi-Gau** [comment]
OK I tracked it down to this line: https://github.com/cpp-lln-lab/CPP_SPM/blob/858f3cb95f5803958384d993845d29573d5db462/src/workflows/bidsCopyRawFolder.m#L82

It makes a list of the modalities to copy for that session but it filters only those that include the task of interest. Not what we want.

But now I realize that removing this filter means we will always copy the `func` folders even if they don't include the task of interest. So we will need to filter things out at the lower level in the `copyModalityDir` subfunction.

**Comment by Remi-Gau** [comment]
we will have to check if this bug still persists as bidsCopyRaw should not transfer that are not about the task of interest

**Comment by Remi-Gau** [comment]
I suspect that this has been fixed a long time ago otherwise @marcobarilari and @Remi-Gau would have encountered this problem many times on their 8 sessions pilot dataset.
