### ISSUE TITLE
bids-matlab (probably) does not like the dir-reversedPhase

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#194]
## Describe your problem in detail

Running analysis with our high-res dataset with bold images for fieldmap correction like `*dir-reversedPhase.nii`

While running any function that parses the bold images using bid-matlab, I get an error. I suspect that this type of bold image is not yet implemented in bids-matlab therefore it does not know what to do with them. 

Though, I think that more than not implemented, the `dir` label is not present among those to read/skip/etc.

## Describe what outcome you expected 

to receive a warning that bids-matlab is skipping that image if not yet implemented as for e.g.  MP2RAGE

### Error message

```matlab
Warning: Ignoring file "sub-pilot001_ses-001_acq-lores_part-mag_inv-2_MP2RAGE.nii" not matching template. 
> In spm_BIDS>parse_filename (line 715)
  In spm_BIDS>parse_subject (line 163)
  In spm_BIDS (line 123)
  In getData (line 74)
  In bidsCopyRawFolder (line 60) 
Warning: Ignoring file "sub-pilot001_ses-002_task-bimotionGrating_dir-reversedPhase_run-1_bold.nii.gz" not matching template. 
> In spm_BIDS>parse_filename (line 715)
  In spm_BIDS>parse_subject (line 182)
  In spm_BIDS (line 125)
  In getData (line 74)
  In bidsCopyRawFolder (line 60) 
Subscript indices must either be real positive integers or logicals.
Error in spm_BIDS>parse_subject (line 184)
        subject.func(end).meta = struct([]); % ?
Error in spm_BIDS (line 125)
            BIDS.subjects(end+1) = parse_subject(BIDS.dir, sub{su}, sess{se});
Error in getData (line 74)
  BIDS = spm_BIDS(derivativesDir);
Error in bidsCopyRawFolder (line 60)
  [group, opt, BIDS] = getData(opt, rawDir);
```

**Comment by Remi-Gau** [comment]
OK I think I fixed that one. 

First of all it seems that the `CPP_SPM` tracks the `bids_matlab` fork of the lab's github organization: so we need to update this one to make sure it is in synch with the `bids-matlab` upstream repo and we have to remember to update the fMRI_template.

And then I check I the list of entities that are used by bids-matlab to parse the filenames of `func` files and `dir´ is not one of them. 

So I created a [branch](https://github.com/cpp-lln-lab/bids-matlab/tree/remi-parse_func) on our bids-matlab to fix that. If you switch your sub-sub-module's branch to this one the problem should be fixed.

I will open a PR on bids-matlab to fix that upstream too and check with Guillaume that this is a bug.

**Comment by marcobarilari** [comment]
> First of all it seems that the CPP_SPM tracks the bids_matlab fork of the lab's github organization: so we need to update this one to make sure it is in synch with the bids-matlab upstream repo and we have to remember to update the fMRI_template.

is it ok in the long run? I mean, does not it imply "more work" to check multiple repos?

> And then I check I the list of entities that are used by bids-matlab to parse the filenames of func files and `dir´ is not one of them.

this confirm my suspect then, skipping MP2RAGE and not dir because it was not among the labels that bids-matlab "knows"

> So I created a branch on our bids-matlab to fix that. If you switch your sub-sub-module's branch to this one the problem should be fixed.

thanks :)

**Comment by Remi-Gau** [comment]
> > First of all it seems that the CPP_SPM tracks the bids_matlab fork of the lab's github organization: so we need to update this one to make sure it is in synch with the bids-matlab upstream repo and we have to remember to update the fMRI_template.
> 
> is it ok in the long run? I mean, does not it imply "more work" to check multiple repos?

yes I am not happy with this multiple changes...

Maybe we should remove the bids-matalb fork of the lab and directly track the upstream. 

But that means we will nevertheless need to regularly update the template repo. I need to look into if we can let the continuous integration to that for us at regular interval and to always track the latest version or the latest commit of the main branch.

But that would also mean that this CI automation would be carried over when creating a new repo with the template. I suspect I can make the CI smart enough to stop doing that if it realizes the name of the current repo is not that of the template anymore.

**Comment by Remi-Gau** [comment]
Continuous integration will soon become my new friend.

**Comment by marcobarilari** [comment]
yes that could be an idea

**Comment by Remi-Gau** [comment]
This should be fixed by the latest merge on bids-matlab: just make sure that your submodules are up to date with the latest commit on the master branch of bids-matlab (or simply do a  `git pull upstream dev`  to get the latest changes in this repo).
