### ISSUE TITLE
FFX specify&estimate fails in case in a run a specific tryal_type specified in the model is missing

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#197]
## Describe your problem in detail

In my design I have 3 condition (A, B and C) and only 1 of them is presented in a run. I have specified my `model.json` file as:

```
{
[...]

  },
  "Steps": [
    {
      "Level": "run",
      "Model": {
        "X": [
          "trial_type.A",
          "trial_type.B",
          "trial_type.C",
          "trial_type.response",
          "trans_x", "trans_y", "trans_z", "rot_x", "rot_y", "rot_z"
        ]
      },

[...]
```

> only 1 of them is presented in a run
means that if in run1 I have condition A, condition B and C are missing.

Same story if I have no responses from the participant (@fedefalag has this problem).

## Describe what outcome you expected 

I don't what should happen in this case, maybe a 'FFX specify&estimate' per run 

### Error message

```
------------------------------------------------------------------------
28-Nov-2020 22:11:21 - Running job #2
------------------------------------------------------------------------
28-Nov-2020 22:11:21 - Running 'fMRI model specification'
28-Nov-2020 22:11:21 - Failed  'fMRI model specification'
Error using spm_run_fmri_spec (line 169)
MultiCond file: sess 1 cond 1 has no onset.
In file "/Users/barilari/data/tools/spm12/config/spm_run_fmri_spec.m" (v6562), function "spm_run_fmri_spec" at line 169.
No executable modules, but still unresolved dependencies or incomplete module inputs.
The following modules did not run:
Failed: fMRI model specification
Skipped: Model estimation
Error using MATLABbatch system
Job execution failed. The full log of this run can be found in MATLAB command window, starting with the lines (look for the line showing the
exact #job as displayed in this error message)
------------------
Running job #2
------------------
```

It says that in sess 1 (run 1) cond 1 (A) has no onset (no entries in trial_type column corresponding to 'A')

**Comment by Remi-Gau** [comment]
yup this is exactly the same issue. defo need to fix that urgently

**Comment by marcobarilari** [comment]
I can help with that, but I need some guidance

**Comment by Remi-Gau** [comment]
I suspect it is a matter of adding an `if` in this par of the code : 

https://github.com/cpp-lln-lab/CPP_SPM/blob/29eab4247de17ead5a54d93178fccd7a85225ee0/src/subject_level/convertOnsetTsvToMat.m#L73

This way you can skip appending stuff to the cells `names`, `onsets` and `durations` if `idx` is empty.

These are the cells that are saved in the mat file you find in each GLM folder (one mat file per run) and that contains the info to input in the FFX batch.

**Comment by Remi-Gau** [comment]
@all-contributors please add @marcobarilari  for bug

**Comment by Remi-Gau** [comment]
@all-contributors please add @fedefalag for bug

**Comment by marcobarilari** [comment]
great! So the if statement will check if `~isempty(idx)`,

 if empty witll skip 

```
% Get the onset and duration of each condition
names{1, iCond} = conditionName;
onsets{1, iCond} = t.onset(idx)'; %#ok<*AGROW,*NASGU>
durations{1, iCond} = t.duration(idx)';
```

though, let's take my case described above, run 1 I have condition B and the responses, now I have a mat file where eg onset looks like this


`A              B              C        Response`
```
[]	1x80 double	[]	1x12double
```

If I skip those conditions that are missing, the shape of this cell will change from 1x4 to 1x2 and condition B will be in the place of condition A. I guess this is not ideal, right?

(I hope it's clear)

**Comment by marcobarilari** [comment]
Actually, it changes nothing because the position in the cell is given by `iCond` in  `onsets{1, iCond}`.

So the script should check run by run if a specific trial_type is in the tsv file and do not modelize those missing. 

errata corrige
> If I skip those conditions that are missing, the shape of this cell will change from 1x4 to 1x2 and condition B will be in the place of condition A. I guess this is not ideal, right?

I think it is ideal, in my example, it is correct that the model in 1 run has only 2 columns (condion A or B or C + response) + motion parameters

**Comment by Remi-Gau** [comment]
Yeah I think it might be cleaner to make those variables "grow" using an `end+1` or an actual counter variable.

Like this.

```
names{1, end+1} = conditionName;
onsets{1, end+1} = t.onset(idx)'; %#ok<*AGROW,*NASGU>
durations{1, end+1} = t.duration(idx)';
```

Or like this : 


```
conditionCounter = 1;
 % for each condition
  for iCond = 1:numel(isTrialType)

    if isTrialType{iCond}

      conditionName = strrep(step.Model.X{iCond}, ...
                             'trial_type.', ...
                             '');

      % Get the index of each condition by comparing the unique names and
      % each line in the tsv files
      idx = find(strcmp(conditionName, conds));

      if ~isempty(idx)      
        % Get the onset and duration of each condition
         names{1, conditionCounter} = conditionName;
         onsets{1, conditionCounter} = t.onset(idx)'; %#ok<*AGROW,*NASGU>
         durations{1, conditionCounter} = t.duration(idx)';

         conditionCounter = conditionCounter + 1;
     end

    end
  end
```

**Comment by Remi-Gau** [comment]
if you start a PR for this I can update the test after. :-)

**Comment by marcobarilari** [comment]
![Screen Shot 2020-11-29 at 12 24 18](https://user-images.githubusercontent.com/38101692/100540516-03520480-323e-11eb-89e4-e994a6be65bc.png)

**Comment by marcobarilari** [comment]
Ok, yes it works like that 🎉 but now I remember that my timings are fu^&*d up starting from zero in run 1 and 4.

**Comment by Remi-Gau** [comment]
> but now I remember that my timings are fu^&*d up starting from zero in run 1 and 4. One problem at the time

Problems that past-you let future-you deal with. :-)
