### ISSUE TITLE
Save thresholded maps for any contrasts

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#212]
You think / need this code to do **save thresholded maps for any contrasts**.

Something is missing / unclear about **I don't know if it is already implemented**.

**Comment by Remi-Gau** [comment]
So it sort of is.

If you want to use the SPM batch you would go batch --> SPM --> stats --> Results Report

You then need to give it the SPM.mat the contrast index and the voxel and cluster threshold and the type of multiple comparison correction.

You then can choose how to export the results in terms of figures or nifti output.

At the moment at the subject the code that handles that is:

Workflow `bidsResults` calls batch `setBatchSubjectLevelResults` that calls `setBatchResults`.

Nothing is computed automatically at the moment.

Users have to specify in `opt.results` which contrast they are interested in as well as the different thresholds.

From the options of the MoAE demo:

```matlab
  % specify the result to compute
  opt.result.Steps(1) = struct( ...                                        % The index for step refers to the index of the step in the model json
                               'Level',  'subject', ...
                               'Contrasts', struct( ...
                                                   'Name', 'listening', ...      % has to match an existing contrast name
                                                   'Mask', false, ...
                                                   'MC', 'FWE', ... FWE, none, FDR
                                                   'p', 0.05, ...
                                                   'k', 0, ...
                                                   'NIDM', true));                 % at the moment the results will onlybe exported as `.ps``but you can ask for an export as NIDM.

  opt.result.Steps(1).Contrasts(2) = struct( ...
                                            'Name', 'listening_inf_baseline', ...
                                            'Mask', false, ...
                                            'MC', 'none', ... FWE, none, FDR
                                            'p', 0.01, ...
                                            'k', 0, ...
                                            'NIDM', true);
```

I suspect we should make export as `.png` the default here:

https://github.com/cpp-lln-lab/CPP_SPM/blob/347ce4ff0f50f36aa2313d632b0ec10a25030396/src/batches/setBatchResults.m#L45

Other things that it would be nice to have

- thresholded SPM 
- montage
- csv table

Having a series of flag in the contrast sub-structure like for `NIDM` above would be the way to go I think.

```matlab
matlabbatch{1}.spm.stats.results.export{1}.png = true;
matlabbatch{1}.spm.stats.results.export{2}.tspm.basename = '<UNDEFINED>';
matlabbatch{1}.spm.stats.results.export{3}.montage.background = '<UNDEFINED>';
matlabbatch{1}.spm.stats.results.export{3}.montage.orientation = '<UNDEFINED>';
matlabbatch{1}.spm.stats.results.export{3}.montage.slices = '<UNDEFINED>';
matlabbatch{1}.spm.stats.results.export{4}.csv = true;
```

And feel free to turn that into some documentation. :-)

**Comment by marcobarilari** [comment]
thanks Remi! yes I am using bidsResults but I am actually interested in the `thresholded SPM` to use those volumes in fsl.

Well, nice viz is the next step.

**Comment by Remi-Gau** [comment]
oh and you can also do that via the graphic interface... But... Well... Why would you want to do THAT? :vomiting_face:

**Comment by marcobarilari** [comment]
> Why would you want to do THAT? 

you mean the manually or the FSL part?

(1) lack of time

(2) way better than SPM and lack of time

**Comment by Remi-Gau** [comment]
ha I meant that you can output the threshold maps once you have use the RESULTS button of SPM and viewed your results.

completely OK viewing the exported results however anyone wants
