### ISSUE TITLE
Problem for task with one run in one ses

### ISSUE THREAD

**Issue by fedefalag** [cpp-lln-lab/CPP_SPM#226]
## Describe your problem in detail
Pipeline fails at bidsSTC for my task face and voicelocalizer (see error below), but not for tasks with several runs.
These two tasks are one in each of my 2 sessions folders. i.e. task-facelocalizer exists only in ses-01, while task-voicelocalizer exists only in ses-02. I've tried to add the run number to the file name, but didn't change.

## Describe what outcome you expected 
I expected the STC to start

## Describe what you got instead
It didn't because of some task/name selection problem (I think)

### Error message

If possible paste below the error message you encountered.

```matlab
 BUILDING STC JOB : STC
71        [fileName, subFuncDataDir] = getBoldFilename( ...
Index exceeds matrix dimensions.

Error in setBatchSTC (line 73)
                                                   subID, sessions{iSes}, runs{iRun}, opt);

Error in bidsSTC (line 51)
      matlabbatch = setBatchSTC(BIDS, opt, subID);
```

**Comment by Remi-Gau** [comment]
hey @fedefalag 

Just to be sure, can you add a print out of the `tree` command to see the content of your dataset.

if you don't have it, run `brew install tree` on Mac.

**Comment by fedefalag** [comment]
Following Marco's suggestion, I paste here the tree of one of my subjects in the derivatives folder. When selecting the voicelocalizer as task of interest, the whole folder of the session containing the task (ses-02 in this case) is copied from raw to derivatives.


derivatives falagiarda$ tree
.
├── dataset_description.json
├── participants.json
├── participants.tsv
├── sub-002
│   ├── ses-01
│   └── ses-02
│       └── func
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-10_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-10_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-10_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-1_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-1_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-1_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-2_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-2_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-2_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-3_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-3_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-3_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-4_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-4_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-4_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-5_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-5_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-5_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-6_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-6_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-6_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-7_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-7_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-7_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-8_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-8_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-8_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-9_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-9_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoAuditory_run-9_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-10_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-10_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-10_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-1_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-1_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-1_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-2_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-2_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-2_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-3_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-3_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-3_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-4_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-4_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-4_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-5_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-5_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-5_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-6_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-6_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-6_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-7_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-7_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-7_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-8_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-8_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-8_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-9_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-9_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoBimodal_run-9_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-10_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-10_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-1_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-1_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-2_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-2_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-3_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-3_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-4_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-4_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-5_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-5_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-6_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-6_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-7_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-7_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-8_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-8_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-9_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoCorrection_run-9_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-10_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-10_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-10_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-1_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-1_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-1_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-2_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-2_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-2_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-3_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-3_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-3_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-4_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-4_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-4_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-5_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-5_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-5_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-6_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-6_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-6_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-7_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-7_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-7_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-8_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-8_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-8_events.tsv
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-9_bold.json
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-9_bold.nii
│           ├── sub-002_ses-02_task-eventrelatedCombiemoVisual_run-9_events.tsv
│           ├── sub-002_ses-02_task-voicelocalizerCombiemo_run-1_bold.json
│           ├── sub-002_ses-02_task-voicelocalizerCombiemo_run-1_bold.nii
│           ├── sub-002_ses-02_task-voicelocalizerCombiemo_run-1_events.tsv
│           ├── sub-002_ses-02_task-voicelocalizerCorrection_bold.json
│           └── sub-002_ses-02_task-voicelocalizerCorrection_bold.nii

**Comment by marcobarilari** [comment]
> hey @fedefalag
> 
> Just to be sure, can you add a print out of the `tree` command to see the content of your dataset.
> 
> if you don't have it, run `brew install tree` on Mac.

this is scary, I said the exact same words.....

**Comment by Remi-Gau** [comment]
I am having trouble reproducing your bug. :-(

I modified the bash script `tests/createDummyDataSet.sh` to add some dummy data to resemble your case.

I then try to run `setBatchSTC` to make sure everything is OK and I don't get an error.

---

Here is an example of what this looks like.

```bash
dummyData/derivatives/cpp_spm/sub-01
├── ses-01
│   ├── anat
│   │   ├── sub-01_ses-01_T1w.json
│   │   └── sub-01_ses-01_T1w.nii
│   └── func
│       ├── asub-01_ses-01_task-vismotion_run-1_bold.nii
│       ├── asub-01_ses-01_task-vismotion_run-2_bold.nii
│       ├── meanusub-01_ses-01_task-vislocalizer_bold.nii
│       ├── rp_sub-01_ses-01_task-vislocalizer_bold.txt
│       ├── s6rsub-01_ses-01_task-vislocalizer_bold.nii
│       ├── s6usub-01_ses-01_task-vislocalizer_bold.nii
│       ├── s6wsub-01_ses-01_task-vislocalizer_bold.nii
│       ├── s6wusub-01_ses-01_task-vislocalizer_bold.nii
│       ├── sub-01_ses-01_task-vislocalizer_bold.nii
│       ├── sub-01_ses-01_task-vislocalizer_events.tsv
│       ├── sub-01_ses-01_task-vismotion_run-1_bold.nii
│       ├── sub-01_ses-01_task-vismotion_run-1_events.tsv
│       ├── sub-01_ses-01_task-vismotion_run-2_bold.nii
│       ├── sub-01_ses-01_task-vismotion_run-2_events.tsv
│       └── sub-01_ses-01_task-voicelocalizer_bold.nii              # voice localiser only in session 1
├── ses-02
│   ├── anat
│   │   └── sub-01_ses-02_T1w.nii
│   └── func
│       ├── asub-01_ses-02_task-vismotion_run-1_bold.nii
│       ├── asub-01_ses-02_task-vismotion_run-2_bold.nii
│       ├── meanusub-01_ses-02_task-vislocalizer_bold.nii
│       ├── rp_sub-01_ses-02_task-vislocalizer_bold.txt
│       ├── s6rsub-01_ses-02_task-vislocalizer_bold.nii
│       ├── s6usub-01_ses-02_task-vislocalizer_bold.nii
│       ├── s6wsub-01_ses-02_task-vislocalizer_bold.nii
│       ├── s6wusub-01_ses-02_task-vislocalizer_bold.nii
│       ├── sub-01_ses-02_task-facelocalizer_bold.nii                # face localiser only in session 2
│       ├── sub-01_ses-02_task-vislocalizer_bold.nii
│       ├── sub-01_ses-02_task-vislocalizer_events.tsv
│       ├── sub-01_ses-02_task-vismotion_run-1_bold.nii
│       ├── sub-01_ses-02_task-vismotion_run-1_events.tsv
│       ├── sub-01_ses-02_task-vismotion_run-2_bold.nii
│       └── sub-01_ses-02_task-vismotion_run-2_events.tsv
|
... # hiding other subjects
|
├── T1w.json
├── task-facelocalizer_bold.json
├── task-vislocalizer_bold.json
├── task-vismotion_bold.json
└── task-voicelocalizer_bold.json
```

```matlab
  %% set up STC  batch for voicelocalizer
  opt.derivativesDir = fullfile(fileparts(mfilename('fullpath')), 'dummyData');
  opt.taskName = 'voicelocalizer';

  opt = checkOptions(opt);

  [~, opt, BIDS] = getData(opt);

  subID = '01';
  matlabbatch = setBatchSTC(BIDS, opt, subID);

  expectedBatch = returnExpectedBatch();
  assertEqual(matlabbatch, expectedBatch);
  
 %% same but for face localizer
  opt.taskName = 'facelocalizer';
  matlabbatch = setBatchSTC(BIDS, opt, subID);

  expectedBatch = returnExpectedBatch();
  assertEqual(matlabbatch, expectedBatch);
```

**Comment by Remi-Gau** [comment]
OK a couple of things to try for you.

```matlab
% get the content of the dataset with bids-matlab
BIDS = bids.layout(path_to_yourt_dataset);

% Check that all the tasks are there for each session
bids.query(BIDS, 'tasks',  'ses',  '01')
bids.query(BIDS, 'tasks',  'ses',  '02')

% seems that your crash is coming from getBoldFilename that uses getInfo to get the name of the file
% check how many nifti files are returned by the following

bids.query(BIDS, 'data', ...
                           'sub', '002', ...
                           'run', [], ...
                           'ses', '02', ...
                           'task', 'voicelocalizerCombiemo', ...
                           'type', 'bold');
```

**Comment by Remi-Gau** [comment]
Seems that this issue highlights the need for a good batch script to help this thing work smoothly right out of the box.

**Comment by marcobarilari** [comment]
> OK a couple of things to try for you.
> 
> ```matlab
> % get the content of the dataset with bids-matlab
> BIDS = bids.layout(path_to_yourt_dataset);
> 
> % Check that all the tasks are there for each session
> bids.query(BIDS, 'tasks',  'ses',  '01')
> bids.query(BIDS, 'tasks',  'ses',  '02')
> 
> % seems that your crash is coming from getBoldFilename that uses getInfo to get the name of the file
> % check how many nifti files are returned by the following
> 
> bids.query(BIDS, 'data', ...
>                            'sub', '002', ...
>                            'run', [], ...
>                            'ses', '02', ...
>                            'task', 'voicelocalizerCombiemo', ...
>                            'type', 'bold');
> ```

interesting suggestion, can this become a section of the docs? Other solution is to make this part of the bids-matlab docs which is maybe better

**Comment by Remi-Gau** [comment]
You mean beyong what's in the jupyter book of bids-matlab?
https://github.com/bids-standard/bids-matlab/blob/master/examples/tutorial.ipynb

**Comment by marcobarilari** [comment]
WUT!? was not aware of this jupiter notebook, sorry :)

**Comment by Remi-Gau** [comment]
Well... I think that having a proper doc would not hurt or being more vocal about the jupyter book could help.
