### ISSUE TITLE
Tests are not running in CI

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_SPM#281]
## Describe your problem in detail

The tests are not running with Travis anymore... Lazy Travis

## Describe what outcome you expected 

I expected Travis to do its job. It has one job!!!

## Describe what you got instead

Nothing. Nada. Rien. Niet.

### Error message

Not even!!!! Travis just ghosted us...

**Comment by CerenB** [comment]
did I break Travis with my latest PR?

**Comment by Remi-Gau** [comment]
not you
