### ISSUE TITLE
duplication of onset files 

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_SPM#292]
## Describe your problem in detail
If I understood right, there's a duplicate of onset files. Not sure if there's a reason to have the duplicates. If yes, please close this issue immediate. If not, here we go... One is inside the `stats-ffx` folder, and one is inside the `func` folder. 
## Describe what outcome you expected 
I thought one of them would be enough. 
## Describe what you got instead
`onsets_sub-011_ses-001_task-RhythmBlock_run-001_events.mat
`
these were all around in the jungle, free running! 

## Error message
No, there's no error message, just it is re-writing the onset files in the `func` folder and making extra ones on `ffx` folder. No harm was done in the process.

**Comment by Remi-Gau** [comment]
I think this is the intended behavior: the idea is to reformat the content of the tsv so it can be passed around to the SPM batch as a mat file (that SPM loves).

If things are coded correctly that mat file should only include the conditions needed for the GLM ran in the folder where it lives.

In other words it means that potentially the conditions in the mat files are subset of the conditions in the tsv file.

Does that make sense?

But once again if you are getting confused someone else will too so I will leave this open and flag it as an something to add to the documentation. What do you say?

**Comment by CerenB** [comment]
@Remi-Gau shall I add some info into the setBatchSubjectLevelGLMSpec.m file? 
It's calling creatingOnset script: 
https://github.com/cpp-lln-lab/CPP_SPM/blob/dev/src/batches/setBatchSubjectLevelGLMSpec.m#L115

Or the documentation should be added elsewhere?
