### ISSUE TITLE
bidsConcatBetaTmaps

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_SPM#293]
## Describe your problem in detail
in dev branch the [bidsConcatBetaTmaps](https://github.com/cpp-lln-lab/CPP_SPM/blob/dev/src/workflows/bidsConcatBetaTmaps.m) function is crashing due to `ffxDir` is not found in removeBetaImgTmaps subfun in line#68. 

@marcobarilari ran this function couple of days ago, did it work fine? if yes, maybe I'm doing something wrong?

### Error message
If possible paste below the error message you encountered.

```
 Undefined function or variable 'ffxDir'.

Error in
bidsConcatBetaTmaps>removeBetaImgTmaps (line
94)
      delete(fullfile(ffxDir, ['con_',
      sprintf('%04d', iCon), '.nii']));

Error in bidsConcatBetaTmaps (line 68)
      removeBetaImgTmaps(beta_maps, t_maps,
      deleteIndBeta, deleteIndTmaps);
```
## proposed solution
if you let me know preferentially where/how you want to call ffxDir, I can implement it and open a PR. I suspect something like 
`ffxDir = getFFXdir(subID, funcFWHM, opt); `
as you call it in the mainfunc but also to call it into subfun as well. If not let me know.

**Comment by marcobarilari** [comment]
thanks for opening this issue, was on my todo :)

yes, the `ffxDir` input is missing the subfun `removeBetaImgTmaps` inside that script. Solution is to add `ffxDir` as input to that func in line 68 and 75 where the function is defined.

**Comment by CerenB** [comment]
yeah that is another solution as well... 
For @fedefalag who might use the script in a short while, I guess one can use the func like below:
`bidsConcatBetaTmaps(opt, funcFWHM,0,0);`

**Comment by fedefalag** [comment]
Yes I did that as I didn't want to delete the betas and maps: worked smoothly! :)

**Comment by Remi-Gau** [comment]
I think this can be closed, no? @CerenB
