### ISSUE TITLE
Plot power spectra optional

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#306]
You think / need this code to do **consider having plot power spectra as optional feature and not default**.

Something is missing / unclear about **on my last dataset (1 subj, 12 runs, 1.6 iso) takes at least 1h30m only that step**.

**Comment by Remi-Gau** [comment]
> **on my last dataset (1 subj, 12 runs, 1.6 iso) takes at least 1h30m only that step**.

# :scream: 

Now I get why the datalad folks have a "WTF"
