### ISSUE TITLE
is _design_after_estimation.png not used anymore?

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_SPM#329]
previously when I ran `bidsFFX` function, this png file was created for before/after estimation and saved in for example `ffx_space-MNI_FWHM-0` folder. but now (maybe due to the `ffx` folder naming changed recently?), I cannot find it. 
Now it is not saved or found not-useful?

**Comment by Remi-Gau** [comment]
let me check : that is definitely not an intentional change.

**Comment by Remi-Gau** [comment]
Ran a demo with last version in `dev` and indeed those figures are gone.... hum... definitely a "bug"
