### ISSUE TITLE
Make some GLM output more BIDS like

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_SPM#333]
For the moment this should only concern the part of the GLM output that SPM does not "reuse" (beta maps, tmaps, con images...) otherwise it will break stuff.

As a usecase example see this: https://github.com/cpp-lln-lab/CPP_ROI/issues/6

**Comment by Remi-Gau** [comment]
Currently `bidsFFX` and  `bidsResults` produce stuff with that would give nightmares to Marie Kondo.

```
spmT_0001_listening_p-0050_k-0_MC-FWE_mask.nii
spmT_0001_listening_p-0050_k-0_MC-FWE.nii	
Montage_listening_p-0050_k-0_MC-FWE_001.png
sub-01_task-auditory_design_after_estimation_001.png
sub-01_task-auditory_design_before_estimation_001.png
onsets_sub-01_task-auditory_events.mat
```

So we can try to make that more BIDS friendly

Stuff relative to a specific contrast result:

In the case the results relative to the first T contrast (stored by SPM in `spmT_0001.nii`) will be outputted like this by BIDS results:
```
sub-01_task-listening_space-MNI_desc-0001_p-0050_k-0_MC-FWE_mask.nii   <---- binarized thresholded t map (cluster mask)
sub-01_task-listening_space-MNI_desc-0001_p-0050_k-0_MC-FWE_spmT.nii   <---- thresholded t map	
sub-01_task-listening_space-MNI_desc-0001_p-0050_k-0_MC-FWE_montage.png <---- Montage relative to this contrast
```

The description entity `desc` is used to store the contrast number used by SPM (`0001` in this case).

We also use the space entity because it might be useful when creating ROIs.


Stuff relative to the GLM in general
```
sub-01_task-auditory_space-MNI_desc-afterEstimation_designmatrix.png
sub-01_task-auditory_space-MNI_desc-beforeEstimation_designmatrix.png
sub-01_task-auditory_space-MNI_onsets.mat
```

**Comment by marcobarilari** [comment]
Looks good! Though, here

```
sub-01_task-listening_space-MNI_desc-0001_p-0050_k-0_MC-FWE_mask.nii   <---- binarized thresholded t map (cluster mask)
sub-01_task-listening_space-MNI_desc-0001_p-0050_k-0_MC-FWE_spmT.nii   <---- thresholded t map	
sub-01_task-listening_space-MNI_desc-0001_p-0050_k-0_MC-FWE_montage.png <---- Montage relative to this contrast
```

the `task` shouldn't be `auditory`? `listening` is the contrast name, isn't it?

Related to this, in case you want to use the task info in the name, I would be a bit worried about losing the contrast name `listening`, it just makes life super easy to identify the file I need instead of looking for the numbers.
