### ISSUE TITLE
subjectNb filed missing error while running bidsFFX

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_SPM#380]
## Describe your problem in detail
I might have done something wrong in the model maybe, but this model worked in previous subject. So I wonder if anyone could give me a tip where I did something wrong... 

I'm analyzing auditory localiser data. While I insert both `audLocalizer` and `visLocalizer` as tasks, and keep the `.nii/.tsv/...` in the same folder (`sub-099/ses-001/func`)

I did run preprocessing, FFX in `sub-001` and now I'm using the same models etc on `sub-099`. Here what I get when I run:
`bidsFFX('specifyAndEstimate', opt, funcFWHM);
`
```

Reference to non-existent field 'subjectNb'.
 
Reference to non-existent field 'subjectNb'.

Error in createFilename>extractInput (line 100)
    subjectNb = cfg.subject.subjectNb;

Error in createFilename>createDirectories (line 113)
    [subjectGrp, subjectNb, sessionNb, modality] = extractInput(cfg);

Error in createFilename (line 49)
    cfg = createDirectories(cfg);

Error in convertOnsetTsvToMat (line 96)
  fullpathOnsetFileName = fullfile(pth, createFilename(p));

Error in createAndReturnOnsetFile (line 26)
  onsetFileName = convertOnsetTsvToMat(opt, tsvFile);

Error in setBatchSubjectLevelGLMSpec (line 114)
      fullpathOnsetFileName = createAndReturnOnsetFile(opt, ...

Error in bidsFFX (line 58)
        matlabbatch = setBatchSubjectLevelGLMSpec(matlabbatch, BIDS, opt, subLabel,
        funcFWHM);
```

Any ideas?

**Comment by Remi-Gau** [comment]
is that on the most recent version of the `dev` branch?

**Comment by Remi-Gau** [comment]
you have both tasks in the model?

**Comment by CerenB** [comment]
I thought I was in `master` branch, but I was in `rel_0.3.0` branch. Now i'm back to `master` and it is working. 
Shall I close the issue?

**Comment by Remi-Gau** [comment]
yup!!!

PS: don't scare me like that.

# :kissing_heart:

**Comment by CerenB** [comment]
@Remi-Gau May I ask how this is possible to face with this issue although I have been on my `imcalc-branch`? That branch wasn't merged into dev (now I opened a PR to request for such merge). 
I'd like to use my `imcalc `branch, so if `dev` branch has this subjectNb issue, that PR should not be merged into `dev`?

**Comment by CerenB** [comment]
Actually even in the master branch, I have this issue now and cannot run FFX... any ideas?

**Comment by CerenB** [comment]
found the issue! 
when `CPP_BIDS` repo (on master branch) is added into the path, `bidsFFX` function using `checkCFG` or at least using something from `CPP_BIDS` repo. 
So is it the case that in `CPP_SPM` repo, you removed `CPP_BIDS` as a submodule and instead only using `bids-matlab` which has similar functions to `CPP-BIDS`? 

when I remove CPP-BIDS from the path by reinitiating matlab, all is good!
