### ISSUE TITLE
`bidsSpatialPrepro(opt)` does not run without prior slice time correction

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#387]
## Describe your problem in detail

in the latest dev branch, `bidsSpatialPrepro(opt)` does not work if STC has not been run.

## Describe what outcome you expected 

To run spatial prepro without STC as first step, this is possible in previous releases right?

### Error message

If possible paste below the error message you encountered.

```
WORKFLOW: SPATIAL PREPROCESSING

 PROCESSING SUBJECT No.: 1 SUBJECT ID : pilot001 

 BUILDING JOB: selecting anatomical image

 BUILDING JOB: realign
Error using validationInputFile (line 62)
This file does not exist:
/Users/barilari/Desktop/data_temp/ses-006_cpp_spm/derivatives/cpp_spm-task-mtMstLocalizerWithStatic/sub-pilot001/ses-006/func/asub-pilot001_ses-006_task-mtMstLocalizerWithStatic_run-001_bold.nii[.gz]

Error in setBatchRealign (line 91)
      file = validationInputFile(subFuncDataDir, boldFilename, prefix);

Error in bidsSpatialPrepro (line 50)
  parfor iSub = 1:numel(opt.subjects)
```

**Comment by Remi-Gau** [comment]
> To run spatial prepro without STC as first step, this is possible in previous releases right?

Nope. Pretty sure that STC would always be run if sufficient info is provided (slice timing info in the json file of BIDS, or inputed in the options structure).

But we could add a `opt.stc.skip` flag if there is a need.

**Comment by marcobarilari** [comment]
you are right, at least in `v1.0.0` I can't run `bidsSpatialPrepro(opt);` without an `a*.nii` file.
