### ISSUE TITLE
setBatchImageCalculation crashes during RFX 

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_SPM#396]
## Describe your problem in detail
I am running 
`bidsRFX('RFX', opt, funcFWHM, conFWHM);`

and when it comes to setBatchImage step, it crashes. 

### Error message
```
BUILDING JOB: image calculation
Error using setBatchImageCalculation (line 62)
The value of 'matlabbatch' is invalid. It must satisfy the function: iscell.

Error in setBatchMeanAnatAndMask (line 67)
  matlabbatch = setBatchImageCalculation(matlabbatch, ...

Error in bidsRFX (line 69)
      matlabbatch = setBatchMeanAnatAndMask(matlabbatch, ...
 


```
When I check in line#62 

```
62    parse(p, varargin{:});
K>> parse(p, varargin{:})
The value of 'matlabbatch' is invalid. It must satisfy the function: iscell.
```
apparently, 
`p.Results` is a struct with no fields.

Any ideas?

**Comment by Remi-Gau** [comment]
I think that initializing the batch with an empty cell here should do.

https://github.com/cpp-lln-lab/CPP_SPM/blob/a9d8c618c5d30d83a148c864f602268f211587a3/src/workflows/bidsRFX.m#L68

```
matlabbatch = {};
```

Can you try and let me know? 

I am slowly trying to start using argparse more in the code base but I have not done it everywhere yet.

**Comment by Remi-Gau** [comment]
Ideally we want to open a PR to change all the `matlabbatch = [];` :-)

**Comment by CerenB** [comment]
oh, OK I was trying to go back in the branches to see what happened! it works before in this [modification](https://github.com/cpp-lln-lab/CPP_SPM/commit/1fcbb033b4af2df69f8eeae030c330ca63b3b35d#diff-948bea455daf5e2f0482e138df087d70ec1fc3e03ca11f0ac00d1c12c8f1d77e).

Now I tried with your suggestion, it worked! thank you so much for quick feedback!

**Comment by Remi-Gau** [comment]
I pushed a commit to fix this on the big fMRIprep PR.

https://github.com/cpp-lln-lab/CPP_SPM/pull/367/commits/bf6177365b3bc15a52e008f0df95e3e41228425d

**Comment by CerenB** [comment]
ok, shall I close this issue? 

in fmriprep_input branch, bids-matlab submodule etc has to be updated compared to dev branch right? is it not recommended to work in fmriprep branch yet?

**Comment by Remi-Gau** [comment]
yeah the fmriprep branch is not quite yet done.

should be soon, but merging it should trigger a new version release because it will change a lot of things.

**Comment by Remi-Gau** [comment]
I can open a PR on the dev branch and just cherry pick the commit I applied on the fmriprep branch.

**Comment by CerenB** [comment]
I did my own branch to keep this change, so if it's only me, then please don't bother. (I'm slightly worried of submodule crashes :))

**Comment by Remi-Gau** [comment]
na it's fine, your branch is based on dev.
I can make a quick and easy PR.

**Comment by CerenB** [comment]
I did try on my local, everything works!
