### ISSUE TITLE
[BUG]: pipeline doesn't run when MarsBar toolbox is not installed

### ISSUE THREAD

**Issue by iqrashahzad14** [cpp-lln-lab/CPP_SPM#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

it stops at slice time correction

### Environment

```markdown
- OS:
- Matlab:
- SPM:
```

**Comment by Remi-Gau** [comment]
The source of this was tracked down to be an issue in the template repo and not CPP_SPM.

To fix this bug you should update the `initEnv` so it looks like this:

https://github.com/cpp-lln-lab/template_datalad_fMRI/blob/39de69c7f535719620ae6c7c22a72f97f8980fd8/code/src/initEnv.m#L103

```
function addDependencies()

    pth = fullfile(fileparts(mfilename('fullpath')), '..');
    addpath(fullfile(pth, 'lib', 'CPP_SPM'));
    initCppSpm();
    addpath(fullfile(pth, 'src'));

end
```
