### ISSUE TITLE
BIDS way of naming the ROIs

### ISSUE THREAD

**Issue by iqrashahzad14** [cpp-lln-lab/CPP_SPM#480]
What is the BIDS way to name and store (Regions of Interest)ROIs which will be used for MVPA?

**Comment by Remi-Gau** [comment]
Copying here what I did put on Slack.


Here is a n example from the face repetition demo

```
CPP_SPM/demos/face_repetition/outputs/derivatives 
╰─⠠⠵ tree cpp_spm-roi

cpp_spm-roi
├── group
│   ├── hemi-L_space-MNI_label-V1d_desc-wang_mask.json
│   ├── hemi-L_space-MNI_label-V1d_desc-wang_mask.nii
│   ├── hemi-L_space-MNI_label-V1v_desc-wang_mask.json
│   ├── hemi-L_space-MNI_label-V1v_desc-wang_mask.nii
│   ├── hemi-R_space-MNI_label-V1d_desc-wang_mask.json
│   ├── hemi-R_space-MNI_label-V1d_desc-wang_mask.nii
│   ├── hemi-R_space-MNI_label-V1v_desc-wang_mask.json
│   └── hemi-R_space-MNI_label-V1v_desc-wang_mask.nii
└── sub-01
    └── roi
        ├── sub-01_space-individual_hemi-L_label-V1d_desc-wang_mask.nii
        ├── sub-01_space-individual_hemi-L_label-V1v_desc-wang_mask.nii
        ├── sub-01_space-individual_hemi-R_label-V1d_desc-wang_mask.nii
        └── sub-01_space-individual_hemi-R_label-V1v_desc-wang_mask.nii
```


There is no "official" way to name ROI in BIDS but I have been applying the BIDS naming principles to name those.

The closest things to ROI naming are the "masks" for the BIDS derivatives: https://bids-specification.readthedocs.io/en/latest/05-derivatives/03-imaging.html#masks

Given that all ROIs in MNI space are going to be the same across subjects, I created a "group" folder (this is not BIDSy but felt better than having a copy of the same file for each subject).

The `desc` entity (description) here is used to denotate the atlas the ROI taken from, so if you are building yours from a localizer you might not need to use it.

**Comment by Remi-Gau** [comment]
there must be a bug somewhere in the demo because in PURE bids `hemi` comes before `space`

**Comment by Remi-Gau** [comment]
Using bids Matlab functions to create bids valid names

```
>> name_spec.ext = '.nii';
>> name_spec.suffix = 'mask';
>> name_spec.entities = struct( ...
                                                    'hemi', 'R', ...
                                                    'space', 'MNI', ...
                                                    'label', 'V1v', ...
                                                    'desc', 'wang');
>> file = bids.File(name_spec);
>> file.filename

hemi-R_space-MNI_label-V1v_desc-wang_mask.nii

```

**Comment by Remi-Gau** [comment]
@all-contributors please add @iqrashahzad14  for bug, doc, question, review, userTesting
