### ISSUE TITLE
SpecifyContrasts does not accept a model without contrasts (commit: d84cb6be)

### ISSUE THREAD

**Issue by fcerpe** [cpp-lln-lab/CPP_SPM#491]
Hi,

as per object, I'm having issues with the `specifiyContrasts` function in `bidsConcatBetaTmaps`. 
More in detail, SpecifyRunLvlContrasts returns nothing and the error says 

```
Error using errorHandling (line 52)
No contrast to build

Error in specifyContrasts (line 64)
    errorHandling(mfilename(), 'noContrast', msg, false, true);

Error in bidsConcatBetaTmaps (line 50)
    contrasts = specifyContrasts(SPM, model);

```
My understanding is that in the model file for the decoding there should not be specific contrasts as in the glm analysis. 
I hope this is clear enough.
Thank you

Filippo

**Comment by Remi-Gau** [comment]
OK I checked out the commit you mentioned and created a separate branch there:

https://github.com/Remi-Gau/CPP_SPM/tree/remi-491_concatenate_beta

**Comment by fcerpe** [comment]
Ok. Thank you for checking it out

**Comment by Remi-Gau** [comment]
OK things run fine on my side with that `bidsConcatBetaTmaps` on one of the demo.

In this case the BIDS model contrast is used to figure out which beta image from each run should be "exported" for your MVPA analysis.

So you do need to specify "dummy contrasts" at the run level Node in your BIDS stats model.

Here is the minimal example that worked on the MoAE demo

```json
{
  "Name": "auditory",
  "BIDSModelVersion": "1.0.0",
  "Description": "contrasts to compute for the FIL MoAE dataset",
  "Input": {
    "task": "auditory"
  },
  "Nodes": [
    {
      "Level": "Run",
      "Name": "run_level",
      "Model": {
        "X": [
          "trial_type.listening",
          "trans_x",
          "trans_y",
          "trans_z",
          "rot_x",
          "rot_y",
          "rot_z"
        ],
        "HRF": {
          "Variables": [
            "trial_type.listening"
          ],
          "Model": "DoubleGamma"
        },
        "Type": "glm",
        "Options": {
          "HighPassFilterCutoffHz": 0.0078,
          "Mask": ""
        },
        "Software": {
          "SPM": {
            "SerialCorrelation": "AR(1)",
            "HRFderivatives": "none"
          }
        }
      },
      "DummyContrasts": {
        "Test": "t",
        "Contrasts": [
          "trial_type.listening"
        ]
      }
    }
  ]
}
```

**Comment by Remi-Gau** [comment]
@fcerpe I will at least add an more meaningful error message because if you got confused, others will too.

**Comment by fcerpe** [comment]
The error was vey dumb on my part: I checked that the essential lines were the same between the "old" and the "new" model file, but I haven't considered all the other lines (dummy contrasts included). 
More than this, if not already implemented, I think a comprehensive guide of "what is what and why is there" for the model file could prevent this issue

**Comment by Remi-Gau** [comment]
Well there is extensive documentation on the BIDS stats model under the form of its specification: 

https://docs.google.com/document/d/1bq5eNDHTb6Nkx3WUiOBgKvLNnaa5OMcGtD0AZ9yms2M/edit?usp=sharing

But this might be more than what you asked for

**Comment by Remi-Gau** [comment]
Actually there is a VERY short version in the doc: 

https://cpp-spm.readthedocs.io/en/dev/set_up.html#bids-model-json-files

See anything that can be improved?

**Comment by fcerpe** [comment]
I should have read the docs, sorry. 

I think in combination they work, don't see some unexplained aspects.

**Comment by Remi-Gau** [comment]
Updated the doc on the BIDS stats model for each section
