### ISSUE TITLE
[ENH]: RFX folder naming

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_SPM#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

Currently RFX folder naming will inherit the one it had from FFX folder (from model.Name being different than the taskName, add this label as desc-)
If in each subject there's no FFX folder, the RFX will not run. Like below:

```markdown
WORKFLOW: GROUP LEVEL GLM

Starting parallel pool (parpool) using the 'local' profile ...
connected to 1 workers.
FOR TASK: RhythmBlock
WILL WORK ON SUBJECTS
    '003'
    '004'
    '006'
    '011'
    '013'
    '017'
    '018'
    '019'
    '020'
    '023'


 BUILDING JOB: create mean anatomical image and mask
 PROCESSING SUBJECT No.: 1 SUBJECT ID : 003 
Error using validationInputFile (line 62)
This file does not exist:
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/RhythmBlock/derivatives/cpp_spm-stats/sub-003/stats/task-RhythmBlock_space-MNI_FWHM-6_desc-badTappers/mask.nii[.gz]

Error in setBatchMeanAnatAndMask (line 48)
    files = validationInputFile(ffxDir,
    'mask.nii');

Error in bidsRFX (line 69)
      matlabbatch =
      setBatchMeanAnatAndMask(matlabbatch,
```

How about having another directory labeling idea, for instance user wants to split the groups, run in only subset of the whole dataset?

**Comment by Remi-Gau** [comment]
OK so the idea is that our current set up forces our subject and group level folders to have the same name, so it makes it hard to run "different" group level analysis based on the same set of estimated subject level analysis.

Am I understanding this correctly?

---

Side note: will use this opportunity to start properly set up a proper mutlsubject demo.

**Comment by CerenB** [comment]
yes. I'm running a group level analysis in which I split my data into 2 (good tappers and bad tappers). But I use the same FFXdir for all. Currently it is not possible to have a RFX folder name `_desc-goodtapper `and `_desc-badtappers ` since there's no such directory in FFX level.

**Comment by Remi-Gau** [comment]
OK that's what I thought, let me check if we can find a dirty fix first so that you can proceed and then try to find a clean way to do this reliably.

**Comment by Remi-Gau** [comment]
ok of course there is the possibility of just renaming the group level folder that was generated the first time and re run the analysis for a different group of subjects but let's not do something THAT dirty.

**Comment by Remi-Gau** [comment]
> ok of course there is the possibility of just renaming the group level folder that was generated the first time and re run the analysis for a different group of subjects but let's not do something THAT dirty.

We are not BARBARIANS.

**Comment by CerenB** [comment]
:( I am a barbarian then...

**Comment by Remi-Gau** [comment]
What I will probably do for this is to use the name of the dataset `Steps` (old name used in the `main` branch) or `Nodes` (official name and used in the dev branch) to define the name of the RFX folder.

https://docs.google.com/document/d/1bq5eNDHTb6Nkx3WUiOBgKvLNnaa5OMcGtD0AZ9yms2M/edit#heading=h.z3o72w76mjd1

https://github.com/cpp-lln-lab/CPP_SPM/blob/827a6382bec5eb5b82d96d18bb1c16887090b45b/demos/vismotion/models/model-visMotionLoc_smdl.json#L107

Also it should be doable to have several dataset step in a single bids_stats model and define in there which files / subjects from the subject level should brought into the dataset level: FitLins in python does that well because they have a full implementation of the bids stats model.

CPP SPM does not have that.

**Comment by Remi-Gau** [comment]
OK it is now possible to have several Nodes of the same level in your BIDS stats model.

Also I am 'flattening the folder structure a bit

See below an example for the JSON and the corresponding 

```json

    {
      "Level": "Dataset",
      "Name": "simple contrast",        < ---- This Node Name will be used in the folder name if different from "dataset_level"
      "GroupBy": [
        "contrast"
      ],
      "Model": {
        "Type": "glm",
        "X": [
          1
        ]
      },
      "DummyContrasts": {
        "Test": "t",
        "Contrasts": [
          "VisMot",                     < ---- This Contrast Name will be used in the folder name
          "VisStat"
        ]
      }
    },
    {
      "Level": "Dataset",
      "Name": "complex contrast",
      "GroupBy": [
        "contrast"
      ],
      "Model": {
        "Type": "glm",
        "X": [
          1
        ]
      },
      "DummyContrasts": {
        "Test": "t",
        "Contrasts": [
          "VisMot_&_VisStat"
        ]
      }
    }
```

In the folder `derivatives/cpp_spm-stats/derivatives/cpp_spm-groupStats` you will have

```bash
.
├── jobs
├── task-vislocalizer_space-IXI549Space_FWHM-6_conFWHM-6_desc-complexContrast_contrast-VisMotVisStat
├── task-vislocalizer_space-IXI549Space_FWHM-6_conFWHM-6_desc-simpleContrast_contrast-VisMot
└── task-vislocalizer_space-IXI549Space_FWHM-6_conFWHM-6_desc-simpleContrast_contrast-VisStat
```
