### ISSUE TITLE
[ENH]: make segmentation inputs `biasfwhm` and `samp` (sampling distance)  possible to change

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

```markdown
add `opt.segment.biasfwhm = 60;` and `opt.segment.samplingDistance = 3;` as default and in `setBatchSegmentation` line 51 and 99


matlabbatch{end}.spm.spatial.preproc.channel.biasfwhm = opt.segment.biasfwhm;

[...]

matlabbatch{end}.spm.spatial.preproc.warp.samp = opt.segment.samplingDistance;
```

### Unclear documentation

```markdown
this goes into dev branch

see [this](https://surfer.nmr.mgh.harvard.edu/fswiki/HighFieldRecon) to see why it is useful
```

**Comment by Remi-Gau** [comment]
More options!!! Yay!!!

**Comment by marcobarilari** [comment]
If u agree I'll take care of this. Will try to identify all the files in which I need to add a new options 🤠.

**Comment by Remi-Gau** [comment]
go for it.

pointers: 
- change the expected default in the tests folder (https://github.com/cpp-lln-lab/CPP_SPM/blob/dev/tests/utils/defaultOptions.m)
- then adapt the default option to match (https://github.com/cpp-lln-lab/CPP_SPM/blob/6a6b2d365fd702fa91c5ecdb1b759893ff5b0252/src/defaults/checkOptions.m#L107)
