### ISSUE TITLE
[BUG]: bidsCreateROI does not output files with the session information

### ISSUE THREAD

**Issue by mcgnunes** [cpp-lln-lab/CPP_SPM#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

To have files in ses folder and renamed with the ses label

### Current Behavior

If the output refers to an ROI for a specific subject and there is a session folder, the output file name misses the 'ses'  label and it actually creates the files not in the ses folder but in 'ses/../roi' 

### Environment

```markdown
- OS:centos
- Matlab: 2017a
- SPM: SPM12 (7771)
- branch: dev
```

**Comment by Remi-Gau** [comment]
@all-contributors please add @mcgnunes] for bug

**Comment by Remi-Gau** [comment]
https://github.com/all-contributors please add @mcgnunes for bug

**Comment by Remi-Gau** [comment]
@all-contributors please add @mcgnunes] for bug

**Comment by Remi-Gau** [comment]
@all-contributors please add @mcgnunes for bug

**Comment by Remi-Gau** [comment]
This should be fixed now and also the roi filenames should be more in accord with BIDS typical filenames.
