### ISSUE TITLE
[BUG] error using lower - check to fix MoAE fmriprep demo

### ISSUE THREAD

**Issue by mwmaclean** [cpp-lln-lab/CPP_SPM#610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

to run in one click

### Current Behavior

Crashes when running the bids stats model after first completing smoothing of fmriprep data

### Error message

```
WORKFLOW: COMPUTING GLM RESULTS

Error using lower
Too many input arguments.

Error in bidsResults (line 151)
    switch lower(node.Level)

Error in cpp_spm>stats (line 248)
    bidsResults(opt);

Error in cpp_spm (line 100)
      stats(args);
 
151     switch lower(node.Level)
```

### Environment

```markdown
- OS: windows pc
- Matlab:R2019b
- SPM:
```

### Branch

```markdown
- branch:
- version:
```

**Comment by Remi-Gau** [comment]
OK the latest system test does crash indeed but for another reason:


https://github.com/cpp-lln-lab/CPP_SPM/runs/6745194165?check_suite_focus=true#step:8:379

**Comment by Remi-Gau** [comment]
OK the last PR now makes the system test with fmriprep data work so maybe try pulling the latest version of the dev branch
