### ISSUE TITLE
[BUG] the check for not rerunning anatomical prepro fails

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

To not re-run anatomical preproc

### Current Behavior

Now, `checkForPreviousSkullStripOutput` checks rightfully if some file from `skullstripping` and `segmentation` live already in the anat folder.

Though, if `opt.skullstrip.do` is not set to `0`, the line

`opt.skullstrip.do = opt.skullstrip.do || segmentationNotAlreadyDone;` where `opt.skullstrip.do` is by default 1 and `segmentationNotAlreadyDone` is 0 cause there are files from segmentation, `opt.skullstrip.do` results in 1 but the matlabbacth fails running because the right images are not queried.

Settin `opt.skullstrip.do = 0;` in the option does the trick.

Possible solution might be to have a force flag also for skullstrip

now:
```
  opt.segment.do = opt.segment.force || segmentationNotAlreadyDone;
  opt.skullstrip.do = opt.skullstrip.do || segmentationNotAlreadyDone;
```

solution 

```
  opt.segment.do = opt.segment.force || segmentationNotAlreadyDone;
  opt.skullstrip.do = opt.skullstrip.force || segmentationNotAlreadyDone;
```

(Hope it is clear)

### Error message

```
Item 'Input Images', field 'val': Value must be either empty, a cellstr or a cfg_dep object.
Item 'Input Images', field 'val': Value must be either empty, a cellstr or a cfg_dep object.
Error using spm_jobman>fill_run_job (line 472)
No executable modules, but still unresolved dependencies or incomplete module inputs.

Error in spm_jobman (line 247)
        sts = fill_run_job('run', cjob, varargin{3:end});

Error in saveAndRunWorkflow (line 32)
      spm_jobman('run', matlabbatch);

Error in bidsSpatialPrepro (line 111)
    saveAndRunWorkflow(matlabbatch, batchName, opt, subLabel);
```

### Environment

```markdown
- OS: mac
- Matlab: 2017b
- SPM: 12
```

### Branch

```markdown
- branch: dev
- version: bloody edge
```

### Anything else?

🤟🏻

**Comment by Remi-Gau** [comment]
Feel free to open a PR.

I suspect that will be easier if you run some of the tests locally

**Comment by Remi-Gau** [comment]
and so we agree

for X being `segment` or `skullstrip`

if `opt.X.do == false`, we never do X
if `opt.X.do == true && opt.X.force == false`, but output of X already exist, we do not do X
if `opt.X.do == true && opt.X.force == true`, we do X in any case
