### ISSUE TITLE
[BUG] Recurrent "Warning: Escaped character '\ ' is not valid. " on windows

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_SPM#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

no warnings when the path to a file or a folder is printed to the screen

### Current Behavior

Seems mostly related to the printing of path to the screen.

List of warning when running MoAE demo

### In bids.matlab

- [x] bids.report>print_to_output (line 654)
- [x] bids.layout>manage_tsv (line 536)

### In cpp spm

- [x] getAnatFilename (line 59)
- [x] getBoldFilename (line 55)
- [x] copyGraphWindownOutput (line 84)
- [x] overwriteDir (line 7)
- [x] setBatchSubjectLevelGLMSpec (line 70)
- [x] getBoldFilenameForFFX (line 52)
- [x] createAndReturnOnsetFile (line 34)
- [x] getData (line 37)

### Error message

Example out of many

```matlab
	- D:Warning: Escaped character '\g' is not valid. See 'doc sprintf' for supported special characters. 
> In cprintf (line 241)
In printToScreen (line 34)
In createAndReturnOnsetFile (line 34)
In setBatchSubjectLevelGLMSpec>returnOnsetsFile (line 239)
In setBatchSubjectLevelGLMSpec (line 105)
In bidsFFX>setAction (line 218)
In bidsFFX (line 108)
In cpp_spm>stats (line 266)
In cpp_spm (line 106)
In moae_01_bids_app (line 102) 
```

### Environment

```markdown
- OS:windows
- Matlab: 2021a
- SPM: 7487
```

### Branch

```markdown
- branch: main
- version: 2.0.0
```

### Anything else?

@mwmaclean 
if you stop any other, add them to this issue

**Comment by mwmaclean** [comment]
still getting a warning for escaped character \c:

Warning: Escaped character '\c' is not valid. See 'doc sprintf' for supported special characters. 
> In cprintf (line 241)
  In printToScreen (line 34)
  In setBatchFactorialDesign>allocateSubjectsContrasts (line 141)
  In setBatchFactorialDesign (line 66)
  In bidsRFX (line 110)
  In cpp_spm>stats (line 268)
  In cpp_spm (line 106)
  In stats (line 77)

**Comment by mwmaclean** [comment]
follow up for escaped characters:

Warning: Escaped character '\c' is not valid. See 'doc sprintf' for supported special characters. 
> In errorHandling (line 60)
  In noSPMmat (line 37)
  In bidsRoiBasedGLM (line 65)
  In statsmidbrain (line 63)
