### ISSUE TITLE
[BUG] bidsFFX fails if using one space only but opt.space was not coerced into cell

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Error message

  if numel(opt.space) > 1
    disp(opt.space);
    msg = sprintf('GLMs can only be run in one space at a time.\n');
    errorHandling(mfilename(), 'tooManySpaces', msg, false, opt.verbosity);
  end

Error using errorHandling (line 52)
GLMs can only be run in one space at a time.

Error in bidsFFX>checkRootNode (line 173)
    errorHandling(mfilename(), 'tooManySpaces', msg, false, opt.verbosity);

Error in bidsFFX (line 73)
  checkRootNode(opt);

Error in step_2_stats (line 14)
bidsFFX('specifyAndEstimate', opt, 'nodeName', 'run');

### Environment

```markdown
- OS:
- Matlab:
- SPM:
```

### Branch

```markdown
- branch:
- version:
```

**Comment by Remi-Gau** [comment]
@marcobarilari 
wasn't there another piece of code you had to comment to make this run?
