### ISSUE TITLE
[BUG] remove clear token from getEnvInfo.m

### ISSUE THREAD

**Issue by mwmaclean** [cpp-lln-lab/CPP_SPM#682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [ ] Mac
- [X] Windows

### Operating system version

```markdown
- Linux Ubuntu 18.04 "bionic beaver"
- Mac OS Version 12 "monterey"
```

### SPM 12 version

- [X] 7771
- [ ] 7487
- [ ] 7219

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

```markdown
- Matlab R2019b
```

### CPP SPM version

- [X] v2.0.0
- [ ] v1.1.0
- [ ] v1.0.0
- [ ] v0.2.0
- [ ] v0.1.0
- [ ] v0.0.1

### CPP SPM branch / commit number

```markdown
- main 29b689dd
- dev 1bda0162
```

### Expected Behavior

run in one click

### Current Behavior

remove `clear tocken` from file

**Comment by Remi-Gau** [comment]
@all-contributors please add @mwmaclean  for bug
