### ISSUE TITLE
[BIDS stats model] "space" as required in json model 

### ISSUE THREAD

**Issue by JeanneCaronGuyon** [cpp-lln-lab/CPP_SPM#696]
If "space" is not written in the json model (at all; not left as blank), than gives the following error.
Basically, while written in main code (opt.space={'MNI152NLin2009cAsym'};), it over-writes it as  {'individual'}    {'IXI549Space'}

Now if I add space in my json model, it runs well. 
"space": ["MNI152NLin2009cAsym"]

Maybe there is a reason for this ? I did not find it as required in the documentation, but maybe I missed it ? Is there a way to have it only written in one of the two either the script or the model ?

**error:**

```matlab
Error using errorHandling (line 56)
GLMs can only be run in one space at a time.

Error in bidsFFX>checkRootNode (line 180)
    errorHandling(mfilename(), 'tooManySpaces', msg, false, opt.verbosity);

Error in bidsFFX (line 73)
  checkRootNode(opt);

Error in cpp_spm>stats (line 289)
        bidsFFX('specifyAndEstimate', opt);

Error in cpp_spm (line 106)
      stats(args);
```

**Comment by Remi-Gau** [comment]
OK try specifying the space in the argument

```matlab
cpp_spm(bids_dir, output_dir, 'subject', ...
        'participant_label', {subject_label}, ...
        'action', 'stats', ...
        'preproc_dir', preproc_dir, ...
        'model_file', model_file, ...
        'space', {'MNI152NLin2009cAsym'}, ...
        'fwhm', 6, ...
        'options', opt);
```

Also in general, the options will be overriden by the argument (whether the default or the one you pass), so in this case even if you specify the space in the options, it will be ignored and only the thing from the argument will count.

Will add some warnings and to make it clearer what is happening.

Also I realized that having `{'individual', 'IXI549Space'}` as default for the `stats` makes no sense and will always fail...

**Comment by Remi-Gau** [comment]
> Should we only pick one ?

The rule "should" be:

- bids_model json files override everything else
- arguments trump options

So in general try to put stuff in json files.

Note you can also specify your options in a json flle and should be able to pass the path to this file instead of defining them a  script.

In case you go down this path the saveOptions, should be of help:

https://github.com/cpp-lln-lab/CPP_SPM/blob/main/src/IO/saveOptions.m

**Comment by Remi-Gau** [comment]
@all-contributors please add @JeanneCaronGuyon for bug
