### ISSUE TITLE
BIDS Stats Model - Warning first mask found is taken

### ISSUE THREAD

**Issue by JeanneCaronGuyon** [cpp-lln-lab/CPP_SPM#710]
Finds several masks (desc_mask) : finds one in the preprocessing folder > anat; and several in the func subfolder (one per run). Should add a "modality" in the model; options; "mask", for it to look only in the anat folder. 
and/or add a comment that says which files it founds and which one it opted for.

**Comment by Remi-Gau** [comment]
will at least throw a warning saying explicitly what images was selected among which.

don't want to assume for the user which exact mask they want to use.
