### ISSUE TITLE
make the pipeline faster

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#72]
see here [Faster_SPM](https://en.wikibooks.org/wiki/SPM/Faster_SPM)

**Comment by Remi-Gau** [comment]
Well we could make mention of that in the `spm_my_defaults.m` file of the repo.

See below.

```
% % Stats defaults
% %==========================================================================
% defaults.stats.maxmem      = 2^29;
```

Recompiling the mex files locally makes sense and this is what is done in the docker recipe `Dockerfile` I think: it just uses `make` to do that.

And to know how to use `make` in your workflow.

```
# install SPM and the relevant patches for octave
RUN mkdir /opt/spm12 \
 && curl -SL https://github.com/spm/spm12/archive/r7487.tar.gz \
  | tar -xzC /opt/spm12 --strip-components 1 \
 && curl -SL https://raw.githubusercontent.com/spm/spm-docker/master/octave/spm12_r7487.patch \
  | patch -p0 \
 && make -C /opt/spm12/src PLATFORM=octave distclean \
 && make -C /opt/spm12/src PLATFORM=octave \
 && make -C /opt/spm12/src PLATFORM=octave install \
 && ln -s /opt/spm12/bin/spm12-octave /usr/local/bin/spm12
```

**Comment by marcobarilari** [comment]
Yes, cool! Thank you.

I was actually thinking about how to implement parallel computing and the use of the gpu to take advantage of the lab monster.

**Comment by Remi-Gau** [comment]
If you want to try to implement `parfor` loops in the pipeline I am all in.

See this [card](https://github.com/cpp-lln-lab/CPP_BIDS_SPM_pipeline/projects/1#card-26401625)

Remember that parfor will be ignored in octave though. :smile:

**Comment by Remi-Gau** [comment]
Actually the whole lot of refactoring should definitely help implement parfor loops.

**Comment by Remi-Gau** [comment]
Work for later

Find a way to implement paralleization in the spatrial prepropreccsing workflow as this is the processing bottleneck at the moment
