### ISSUE TITLE
Compatibility issue with Octave 5.x and spm v.7487

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#73]
I was playing with the `visMotion` dataset and could not run the analysis in octave (5.1). The `test_getData` fails 

```octave
FOR TASK: vismotion
error: BIDS dataset description could not be read.
error: called from
    spm_BIDS at line 69 column 5
    getData at line 53 column 6
    test_getData at line 15 column 9
```
`spm_check_installation`

```octave
error: SPM uses a number of MEX files, which are compiled functions.
These need to be compiled for the various platforms on which SPM
is run. It seems that the compiled files for your computer platform
are missing or not compatible. See
   https://www.wikibooks.org/wiki/SPM#Installation
   /Users/barilari/data/tools/spm12/src/Makefile
for information about how to compile MEX files for x86_64-apple-darwin18.7.0
in Octave 5.2.0.
error: called from
    spm_check_installation>check_basic at line 152 column 5
    spm_check_installation at line 28 column 9
```
from the [spm wiki](https://en.wikibooks.org/wiki/SPM/Octave)

> You need to use the latest versions of SPM12 and GNU Octave (5.2).

and if I run the MEX compilation no problems come up.

So my conclusion is that to run spm on octave 5.x I need the v7771.

LMK what do you think and if it would be the case to test the pipeline with the new spm/octave. Do you think that there would be big problem of incompatibility n/w our code and the new spm or one can upgrade thoughtless?

I tried for fun so no need to make decisions now, no major problem to solve.

**Comment by Remi-Gau** [comment]
Hum... Interesting.
Did you try upgrading to octave 5.2?

**Comment by marcobarilari** [comment]
Sorry, I somehow missed your reply. It is already octave 5.2

**Comment by marcobarilari** [comment]
try to compile spm on octave 

```
  # install SPM and the relevant patches for octave
  - git clone https://github.com/spm/spm12.git --depth 1
  - make -C spm12/src PLATFORM=octave distclean
  - make -C spm12/src PLATFORM=octave
  - make -C spm12/src PLATFORM=octave install
```

**Comment by Remi-Gau** [comment]
Will close this for now but let's reopen if needed but this feels more like an SPM / octave issue than a CPP SPM issue
