### ISSUE TITLE
Update doc BIDS Stats

### ISSUE THREAD

**Issue by JeanneCaronGuyon** [cpp-lln-lab/CPP_SPM#745]
Explicitly say that if you specify one edge, you need all edges to be defined if you want previous ones to be analyzed 
Maybe put a warning or validating thing to say that not all nodes are used if only one edge is specified

**Comment by Remi-Gau** [comment]
Adding a warning to the validation made by BIDS matlab to warn that some nodes are not included in the Edges.

https://github.com/bids-standard/bids-matlab/blob/c450a75b936fc5da2755d1b8163a4197f4848f57/%2Bbids/Model.m#L600
