### ISSUE TITLE
try to standardize order of input arguments into functions

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_SPM#82]

**Comment by marcobarilari** [comment]
wait until the repo is safe with more tests

**Comment by Remi-Gau** [comment]
### input arguments

Suggestion for ordering: from more general to more specific

BIDS  > opt > subject > session > run 

- `BIDS` (from `getData`) restrict the set of possible analysis one can run to this BIDS data set 
- `opt` restricts this set even further
- `subject` /  `session` / `run` even more

```matlab
% OK
varargout = getInfo(BIDS, opt, subID, info, varargin)

% not OK
varargout = getInfo(subID, BIDS, opt, info, varargin) 
```

### output arguments

Try to return them in order of importance first and in order of appearance otherwise.

### exceptions 

If function creates or modifies a batch then `matlabbatch` is the first `argin` and first `argout`.

If a function performs an "action" to be chosen from a one of several strings (with a switch statement), this string comes as first `argin` or second if `matlabbatch` is first. 

This applies even for optional argument. <--- not sure about that one.


```matlab
% OK
varargout = getInfo('filename', BIDS, opt, subID, varargin)
[matlabbatch, voxDim] = setBatchRealign(matlabbatch, [action = 'realign',] BIDS, opt, subID)

% not OK
varargout = getInfo(BIDS, opt, subID, 'filename', varargin) % 'filename' is the name of the "action" or the info to get in this case
[matlabbatch, voxDim] = setBatchRealign(BIDS, opt, subID, matlabbatch, [action = 'realign']) % batch and action should go first
```


@marcobarilari @CerenB 


Does this make sense?
